CREATE DATABASE IF NOT EXISTS manutencao_tds2026;
USE manutencao_tds2026;

CREATE TABLE IF NOT EXISTS usuarios(
	id INT PRIMARY KEY AUTO_INCREMENT,
	nome VARCHAR(200) NOT NULL,
    email VARCHAR(200) NOT NULL,
    senha VARCHAR(245) NOT NULL,
    permissao ENUM('ADMIN','GESTOR','NORMAL') NOT NULL DEFAULT 'NORMAL'
);

--- ISSO AQ É SÓ A BASE PARA EU CONSEGUIR TESTAR O LOGIN E TAL, DPS ADICIONEM AQ O RESTANTE. ---